networks:
    proxy:
        external: true

services:
    app:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        container_name: php.${APP_NAME}
        restart: unless-stopped
        volumes:
            - .:/var/www
        working_dir: /var/www
        networks:
            - proxy

    nginx:
      image: nginx:stable-alpine
      restart: unless-stopped
      ports:
        - "80:80"
      volumes:
        - ./:/var/www
        - ./docker/nginx/:/etc/nginx/conf.d/
      networks:
        - proxy

    mariadb:
      image: mariadb:latest
      container_name: mariadb
      environment:
        MYSQL_ROOT_PASSWORD: "kJ047R;l*:5v"
      ports:
        - "3306:3306"
      volumes:
        - mariadb_data:/var/lib/mysql
      networks:
        - proxy

    node:
        image: node:18
        container_name: node.${APP_NAME}
        environment:
          - VITE_HMR_HOST=${VITE_HMR_HOST}
          - VITE_HMR_PORT=${VITE_HMR_PORT}
        ports:
            - "5173:5173"
        volumes:
            - ./:/var/www
        working_dir: /var/www
        entrypoint: /var/www/docker/scripts/node.sh
        depends_on:
            - app
        networks:
            - proxy
volumes:
  mariadb_data:

